[package]
name = "poly_project"
version = "0.0.0"
authors = [
    "cyphersnake cyphersnake@pm.me",
]
edition = "2021"
license = "MIT"


[[bin]]
name = "tree_keeper"
path = "src/tree_keeper.rs"

[[bin]]
name = "changer"
path = "src/changer.rs"

[dependencies]
