[package]
name = "tree_keeper"
edition = "2021"

[dependencies]
clap = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

poly_project = { path = "../.." }
